# Generated by Django 4.1.5 on 2023-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesforbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesforbooking',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default='1', max_length=2),
        ),
        migrations.DeleteModel(
            name='DaysForBooking',
        ),
    ]
