# Generated by Django 4.1.5 on 2023-01-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesforbooking', '0002_alter_timesforbooking_day_delete_daysforbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesforbooking',
            name='day',
            field=models.TextField(),
        ),
    ]
