# Generated by Django 4.1.5 on 2023-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_dateday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dateday',
        ),
    ]
